[package]
edition = "2021"
name = "jsdt-ddns-client"
version = "0.0.0"

[dependencies]
eventsource-client = "0.11.0"
futures = "^0"
tokio = { version = "^1", features = ["macros", "rt"] }
toml = "^0"
